### ISSUE TITLE
Unable to search for your StackPath site

### ISSUE THREAD

**Issue by sagarspatil** [stackpath/stackpath-wordpress#3]
I have created a site on StackPath. Changed DNS (A, CNAME) record to StackPath. I've entered the correct API client and secret. When I click on submit, this is the error I get -
Loading account stacks
Loading sites from SSL test error Unable to load sites
Unable to search for your StackPath site. Please refresh this page and try again.

I've opened a support ticket with StackPath and included this url and asked them to forward it to you. The support ticket includes the website details along with temporary access. Let me know if you need anything else.

WordPress - 5.4.1
PHP - 7.3.14
Server - Apache
Hosting - GoDaddy Web Hosting with cPanel

**Comment by klaude** [comment]
Howdy, @sagarspatil. Thanks for the issue, and thanks for hitting up our support team. I don't have access to our support system (yet), but I can at least help see if the error is because of a problem with the plugin or a problem with your account. 

The page in the plugin that finds your StackPath series launches off a series of AJAX calls to find your stacks and then find sites in your stacks. We'll need to see what it's sending to StackPath and what StackPath's response is. 

Open your Wordpress installation's `wp-config.php` file, set `WP_DEBUG` to `true`, and set `WP_DEBUG_LOG` to a [valid log value](https://wordpress.org/support/article/debugging-in-wordpress/#wp_debug_log). That tells the plugin to log StackPath API requests and responses to the Wordpress debug log, however it's configured for your site. After saving your config file try to search for your StackPath service again and look for new entries in your log file. 

Can you paste the API calls and responses and any PHP errors that you see when the plugin is looking for your sites? Make sure to hide any personal or StackPath account information from them before pasting them here. Knowing the full error the plugin is getting should point to the problem. Thanks a lot!

**Comment by sagarspatil** [comment]
@klaude Thanks for replying. Here's the error log.

[12-May-2020 12:16:01 UTC] PHP Fatal error:  Uncaught TypeError: Argument 7 passed to StackPath\Site::__construct() must be of the type array, null given, called in /home/pd5nsb9rts61/public_html/wp-content/plugins/stackpath-wordpress-v0.2.0/src/Site.php on line 177 and defined in /home/pd5nsb9rts61/public_html/wp-content/plugins/stackpath-wordpress-v0.2.0/src/Site.php:131
Stack trace:
#0 /home/pd5nsb9rts61/public_html/wp-content/plugins/stackpath-wordpress-v0.2.0/src/Site.php(177): StackPath\Site->__construct('b2b39fcf-f5b0-4...', 'd5496aa8-50c9-4...', 'miamorofficial....', 'ACTIVE', Array, Array, NULL, NULL, false, Object(DateTime), Object(DateTime))
#1 /home/pd5nsb9rts61/public_html/wp-content/plugins/stackpath-wordpress-v0.2.0/src/Site.php(203): StackPath\Site::fromResult(Object(stdClass))
#2 /home/pd5nsb9rts61/public_html/wp-content/plugins/stackpath-wordpress-v0.2.0/src/WordPress/Plugin/AjaxActions.php(45): StackPath\Site::findAll(Object(StackPath\Stack), Object(StackPath\API\Client))
#3 /home/pd5nsb9rts61/public_html/wp-includes/class-wp-hook.php in /home/pd5nsb9rts61/public_html/wp-content/plugins/stackpath-wordpress-v0.2.0/src/Site.php on line 131

Does this help. Do you need anything else to resolve this issue?

**Comment by klaude** [comment]
That's perfect, thanks! 

It looks like your sites came back from the StackPath API with empty `shieldPopCodes` and `apiLoginUrls` fields. The plugin was expecting an array, so it gave up with a fatal error. This looks to be more an error with the plugin than your StackPath service. These two fields are unused by our platform, so we recently deprecated them. I bet that has something to do with this. 

I'll have an update out today that can handle these situations a bit better. Thanks!

**Comment by klaude** [comment]
I believe I've got this fixed. Please give [version 0.2.1](https://github.com/stackpath/stackpath-wordpress/releases/tag/v0.2.1) a try and let us know if this works for you. Thanks!

**Comment by sagarspatil** [comment]
Whoops!

Plugin could not be activated because it triggered a fatal error.

Warning: require_once(/var/www/html/wp-content/plugins/stackpath-wordpress-v0.2.1/vendor/autoload.php): failed to open stream: No such file or directory in /var/www/html/wp-content/plugins/stackpath-wordpress-v0.2.1/stackpath.php on line 47

Fatal error: require_once(): Failed opening required '/var/www/html/wp-content/plugins/stackpath-wordpress-v0.2.1/vendor/autoload.php' (include_path='.:/usr/share/php') in /var/www/html/wp-content/plugins/stackpath-wordpress-v0.2.1/stackpath.php on line 47

**Comment by klaude** [comment]
Whoops indeed! I've re-uploaded the 0.2.1 zip file with the autoloader in it. Apologies for that! Let me know how that one looks. I'll get a proper build script put into this so this doesn't happen again.

**Comment by klaude** [comment]
Please let us know if this is still an issue, @sagarspatil. If we don't hear back I'll assume everything is working with version 0.2.1 and will close this issue at the end of the day today. Thanks!

**Comment by klaude** [comment]
I'm gonna go ahead and close this out. Please open another issue if version 0.2.1 doesn't do the trick. Thanks!
