### ISSUE TITLE
Composer support

### ISSUE THREAD

**Issue by chrisdpeters** [stackpath/stackpath-wordpress#5]
Hi, I tried adding this Git repo to Composer:

```json
{
  "name": "yadda/yadda",
  "license": "proprietary",
  "repositories": [
    {
      "type": "vcs",
      "url": "https://github.com/stackpath/stackpath-wordpress.git"
    }
  ],
  "extra": {
    "installer-paths": {
      "wp-content/plugins/{$name}/": ["type:wordpress-plugin"]
    }
  },
  "require": {
    "stackpath/stackpath-wordpress": "master"
  }
}

```

But I get this error when running `composer update`:

```
[Composer\Repository\InvalidRepositoryException]                                                                                                  
  No valid composer.json was found in any branch or tag of https://github.com/stackpath/stackpath-wordpress.git, could not load a package from it.
```

Same issue if I specify a Git tag.

**Comment by klaude** [comment]
Howdy, @chrisdpeters . Thanks for the issue!

You're seeing that error because the plugin doesn't have a `composer.json` file. When we first started on the plugin composer wasn't entirely compatible with Wordpress plugin management and development. Are you using [WPackagist](https://wpackagist.org/) to try to pull the plugin in? I can do some research and see what, if anything, would have to change to support installation through composer.

**Comment by chrisdpeters** [comment]
@klaude No, I am not using WPackagist. I am trying to set up the GitHub repo for the plugin as a source in my project's `composer.json`. (See the `repositories` section in my example above where I try to point it to GitHub.)

Anecdotally, I was just able to install another dependency directly from GitHub just fine. [Here is what their `composer.json` looks like](https://github.com/voceconnect/voce-settings-api/blob/master/composer.json) if it would give you any hints. I don't develop WP plugins, so I can't give you any further pointers.

Here is how I'm configuring my project's `composer.json` to hook to their Git repo, which looks very similar to my example in the original issue description.

```json
{
  "name": "yadda/yadda",
  "license": "proprietary",
  "repositories": [
    {
      "type": "vcs",
      "url": "https://github.com/voceconnect/voce-settings-api.git"
    }
  ],
  "extra": {
    "installer-paths": {
      "wp-content/plugins/{$name}/": ["type:wordpress-plugin"]
    }
  },
  "require": {
    "voceconnect/voce-settings-api": "0.5.4"
  }
}
```

**Comment by klaude** [comment]
My apologies for the delay in this reply. That's a pretty cool way to do it. I'm a huge fan of composer but thought it wasn't really used in the WordPress world. 

We've got a `composer.json` file, but I've only used it for building an autoloader and installing development dependencies outside of WordPress. I think this is probably caused by a lack of a `name` directive in the file. Composer is looking for a dependency called "stackpath/stackpath-wordpress", but it only knows to get that from the composer config file. It won't infer it from the repository name. 

I'll add `name` and a few other root level options to the file. That should clear this up.

**Comment by klaude** [comment]
All done! @chrisdpeters, please give it a try again and let me know what happens. Try using the "dev-master" version if "master" doesn't work. If neither of those work please report back with the error message you're getting and we'll see what to do next. Thanks!

**Comment by chrisdpeters** [comment]
Thank you, @klaude. I am out this week and will give it a try on Monday. I'll let you know either way. 👍

**Comment by klaude** [comment]
Thanks much. I'll leave this issue open for ya. Enjoy your time out!

**Comment by chrisdpeters** [comment]
@klaude That fixed it. I figured it would be some small metadata detail. Thank you for taking a minute to give it a try.

Yeah, this may not be the most popular way of installing WP plugins, but I couldn't live with the status quo after coming over from the Ruby on Rails world!

**Comment by klaude** [comment]
Hey awesome! I'm glad it's working. 

I hear ya. I'm used to the "right way" of PHP development. Writing for WordPress is like stepping 15 years back in time in many respects. 

Please shout out if there's anything else we can do for you. Thanks!
